---
- name: Converge
  hosts: all
  tasks:
    - name: Include chameleon.periodic_task
      include_role:
        name: chameleon.periodic_task
      vars:
        task_name: foo
        task_command: /bin/echo foo
